class DummyDataService {
  static Map<String, List<Map<String, dynamic>>> getHospitalsByCity() {
    return {
      "Pune": [
        {
          "name": "Ruby Hall Clinic",
          "distance": "2.1 km",
          "distanceKm": 2.1,
          "queue": 10,
          "beds": {"general": 6, "icu": 2},
          "specialties": ["Cardiology", "Orthopedics"],
          "rating": 4.5,
          "phone": "+91-20-6645-5100",
          "address": "40, Sassoon Road, Pune",
        },
        {
          "name": "Jehangir Hospital",
          "distance": "3.5 km",
          "distanceKm": 3.5,
          "queue": 8,
          "beds": {"general": 4, "icu": 1},
          "specialties": ["Neurology", "Pediatrics"],
          "rating": 4.3,
          "phone": "+91-20-6681-5000",
          "address": "32, Sassoon Road, Pune",
        },
        {
          "name": "Sassoon General Hospital",
          "distance": "1.8 km",
          "distanceKm": 1.8,
          "queue": 20,
          "beds": {"general": 10, "icu": 3},
          "specialties": ["Emergency", "General Medicine"],
          "rating": 3.9,
          "phone": "+91-20-2612-8000",
          "address": "Near Pune Station, Pune",
        },
        {
          "name": "KEM Hospital",
          "distance": "4.2 km",
          "distanceKm": 4.2,
          "queue": 5,
          "beds": {"general": 8, "icu": 4},
          "specialties": ["Oncology", "Surgery"],
          "rating": 4.1,
          "phone": "+91-20-6125-5000",
          "address": "Rasta Peth, Pune",
        },
        {
          "name": "Deenanath Mangeshkar Hospital",
          "distance": "6.0 km",
          "distanceKm": 6.0,
          "queue": 14,
          "beds": {"general": 12, "icu": 5},
          "specialties": ["Multi-Specialty", "Transplant"],
          "rating": 4.7,
          "phone": "+91-20-4015-1000",
          "address": "Erandwane, Pune",
        },
      ],

      "Mumbai": [
        {
          "name": "Lilavati Hospital",
          "distance": "5.2 km",
          "distanceKm": 5.2,
          "queue": 12,
          "beds": {"general": 7, "icu": 2},
          "specialties": ["Cardiology", "Neurosurgery"],
          "rating": 4.6,
          "phone": "+91-22-2675-1000",
          "address": "A-791, Bandra Reclamation, Mumbai",
        },
        {
          "name": "Kokilaben Hospital",
          "distance": "4.0 km",
          "distanceKm": 4.0,
          "queue": 6,
          "beds": {"general": 5, "icu": 2},
          "specialties": ["Oncology", "Robotic Surgery"],
          "rating": 4.8,
          "phone": "+91-22-3066-1000",
          "address": "4 Dadabhai Road, Andheri, Mumbai",
        },
        {
          "name": "Hinduja Hospital",
          "distance": "3.1 km",
          "distanceKm": 3.1,
          "queue": 9,
          "beds": {"general": 9, "icu": 3},
          "specialties": ["Gastroenterology", "Urology"],
          "rating": 4.4,
          "phone": "+91-22-2445-2222",
          "address": "Veer Savarkar Marg, Mahim, Mumbai",
        },
        {
          "name": "Breach Candy Hospital",
          "distance": "2.3 km",
          "distanceKm": 2.3,
          "queue": 4,
          "beds": {"general": 6, "icu": 2},
          "specialties": ["Pediatrics", "Gynecology"],
          "rating": 4.5,
          "phone": "+91-22-2367-1888",
          "address": "60 Bhulabhai Desai Road, Mumbai",
        },
        {
          "name": "KEM Hospital Mumbai",
          "distance": "6.5 km",
          "distanceKm": 6.5,
          "queue": 30,
          "beds": {"general": 20, "icu": 8},
          "specialties": ["Emergency", "Trauma", "Burns"],
          "rating": 3.8,
          "phone": "+91-22-2410-7000",
          "address": "Acharya Donde Marg, Parel, Mumbai",
        },
      ],

      "Delhi": [
        {
          "name": "AIIMS Delhi",
          "distance": "6.3 km",
          "distanceKm": 6.3,
          "queue": 25,
          "beds": {"general": 15, "icu": 5},
          "specialties": ["All Specialties", "Research"],
          "rating": 4.9,
          "phone": "+91-11-2659-3308",
          "address": "Sri Aurobindo Marg, New Delhi",
        },
        {
          "name": "Fortis Escorts Heart Institute",
          "distance": "3.2 km",
          "distanceKm": 3.2,
          "queue": 9,
          "beds": {"general": 6, "icu": 2},
          "specialties": ["Cardiology", "Cardiac Surgery"],
          "rating": 4.6,
          "phone": "+91-11-4713-5000",
          "address": "Okhla Road, New Delhi",
        },
        {
          "name": "Max Super Specialty Hospital",
          "distance": "4.8 km",
          "distanceKm": 4.8,
          "queue": 11,
          "beds": {"general": 10, "icu": 4},
          "specialties": ["Neurology", "Orthopedics"],
          "rating": 4.5,
          "phone": "+91-11-2651-5050",
          "address": "Saket, New Delhi",
        },
        {
          "name": "Apollo Hospital Delhi",
          "distance": "5.5 km",
          "distanceKm": 5.5,
          "queue": 7,
          "beds": {"general": 11, "icu": 4},
          "specialties": ["Oncology", "Transplant"],
          "rating": 4.7,
          "phone": "+91-11-2692-5858",
          "address": "Sarita Vihar, New Delhi",
        },
        {
          "name": "Safdarjung Hospital",
          "distance": "2.1 km",
          "distanceKm": 2.1,
          "queue": 35,
          "beds": {"general": 25, "icu": 10},
          "specialties": ["Emergency", "General Surgery"],
          "rating": 3.7,
          "phone": "+91-11-2673-0000",
          "address": "Ansari Nagar East, New Delhi",
        },
      ],

      "Bengaluru": [
        {
          "name": "Manipal Hospital",
          "distance": "2.7 km",
          "distanceKm": 2.7,
          "queue": 7,
          "beds": {"general": 5, "icu": 1},
          "specialties": ["Neurology", "Spine Surgery"],
          "rating": 4.5,
          "phone": "+91-80-2502-4444",
          "address": "98, HAL Airport Road, Bengaluru",
        },
        {
          "name": "Apollo Hospitals Bangalore",
          "distance": "3.9 km",
          "distanceKm": 3.9,
          "queue": 11,
          "beds": {"general": 6, "icu": 2},
          "specialties": ["Cardiology", "Oncology"],
          "rating": 4.6,
          "phone": "+91-80-2941-0000",
          "address": "154/11, Bannerghatta Main Road, Bengaluru",
        },
        {
          "name": "Narayana Health City",
          "distance": "8.1 km",
          "distanceKm": 8.1,
          "queue": 15,
          "beds": {"general": 18, "icu": 7},
          "specialties": ["Cardiac", "Transplant", "Pediatric Cardiac"],
          "rating": 4.8,
          "phone": "+91-80-7122-2200",
          "address": "258/A, Bommasandra, Bengaluru",
        },
        {
          "name": "Fortis Hospital Bangalore",
          "distance": "5.3 km",
          "distanceKm": 5.3,
          "queue": 8,
          "beds": {"general": 8, "icu": 3},
          "specialties": ["Orthopedics", "Gastroenterology"],
          "rating": 4.4,
          "phone": "+91-80-6621-4444",
          "address": "14, Cunningham Road, Bengaluru",
        },
      ],

      "Hyderabad": [
        {
          "name": "KIMS Hospital",
          "distance": "3.4 km",
          "distanceKm": 3.4,
          "queue": 9,
          "beds": {"general": 8, "icu": 3},
          "specialties": ["Multi-Specialty", "Transplant"],
          "rating": 4.5,
          "phone": "+91-40-4488-5000",
          "address": "1-8-31/1, Minister Road, Hyderabad",
        },
        {
          "name": "Apollo Hospitals Hyderabad",
          "distance": "5.1 km",
          "distanceKm": 5.1,
          "queue": 13,
          "beds": {"general": 10, "icu": 4},
          "specialties": ["Cardiology", "Neurology"],
          "rating": 4.7,
          "phone": "+91-40-2360-7777",
          "address": "Jubilee Hills, Hyderabad",
        },
        {
          "name": "Yashoda Hospitals",
          "distance": "2.2 km",
          "distanceKm": 2.2,
          "queue": 6,
          "beds": {"general": 7, "icu": 2},
          "specialties": ["Oncology", "Gastroenterology"],
          "rating": 4.4,
          "phone": "+91-40-4567-4567",
          "address": "Behind Hari Hara Kala Bhavan, Hyderabad",
        },
        {
          "name": "Care Hospitals",
          "distance": "4.0 km",
          "distanceKm": 4.0,
          "queue": 10,
          "beds": {"general": 6, "icu": 2},
          "specialties": ["Emergency", "Critical Care"],
          "rating": 4.3,
          "phone": "+91-40-3041-8888",
          "address": "Exhibition Road, Hyderabad",
        },
      ],

      "Chennai": [
        {
          "name": "Apollo Hospitals Chennai",
          "distance": "3.7 km",
          "distanceKm": 3.7,
          "queue": 14,
          "beds": {"general": 12, "icu": 5},
          "specialties": ["Multi-Specialty", "Transplant"],
          "rating": 4.8,
          "phone": "+91-44-2829-3333",
          "address": "21, Greams Lane, Chennai",
        },
        {
          "name": "MIOT International",
          "distance": "6.2 km",
          "distanceKm": 6.2,
          "queue": 8,
          "beds": {"general": 9, "icu": 4},
          "specialties": ["Orthopedics", "Sports Medicine"],
          "rating": 4.6,
          "phone": "+91-44-4200-2288",
          "address": "4/112 Mount Poonamallee Road, Chennai",
        },
        {
          "name": "Fortis Malar Hospital",
          "distance": "2.9 km",
          "distanceKm": 2.9,
          "queue": 5,
          "beds": {"general": 5, "icu": 2},
          "specialties": ["Cardiology", "Neurosurgery"],
          "rating": 4.5,
          "phone": "+91-44-4289-2222",
          "address": "52, 1st Main Road, Adyar, Chennai",
        },
      ],

      "Kolkata": [
        {
          "name": "AMRI Hospitals",
          "distance": "2.5 km",
          "distanceKm": 2.5,
          "queue": 8,
          "beds": {"general": 7, "icu": 3},
          "specialties": ["Multi-Specialty", "Neurology"],
          "rating": 4.4,
          "phone": "+91-33-6606-3800",
          "address": "JC-16&17, Sector III, Salt Lake, Kolkata",
        },
        {
          "name": "Fortis Hospital Kolkata",
          "distance": "4.1 km",
          "distanceKm": 4.1,
          "queue": 11,
          "beds": {"general": 8, "icu": 3},
          "specialties": ["Cardiology", "Oncology"],
          "rating": 4.5,
          "phone": "+91-33-6628-4444",
          "address": "730 Anandapur, EM Bypass, Kolkata",
        },
        {
          "name": "SSKM Hospital",
          "distance": "1.6 km",
          "distanceKm": 1.6,
          "queue": 28,
          "beds": {"general": 22, "icu": 8},
          "specialties": ["Emergency", "Trauma", "Teaching"],
          "rating": 3.8,
          "phone": "+91-33-2223-3564",
          "address": "244, AJC Bose Road, Kolkata",
        },
      ],

      "Ahmedabad": [
        {
          "name": "Apollo Hospitals Ahmedabad",
          "distance": "4.3 km",
          "distanceKm": 4.3,
          "queue": 9,
          "beds": {"general": 8, "icu": 3},
          "specialties": ["Cardiology", "Orthopedics"],
          "rating": 4.5,
          "phone": "+91-79-6670-1800",
          "address": "Plot 1A, BHAT, Gandhinagar Highway, Ahmedabad",
        },
        {
          "name": "Sterling Hospital",
          "distance": "2.8 km",
          "distanceKm": 2.8,
          "queue": 6,
          "beds": {"general": 6, "icu": 2},
          "specialties": ["Multi-Specialty", "Pediatrics"],
          "rating": 4.4,
          "phone": "+91-79-4000-1000",
          "address": "Memnagar Road, Ahmedabad",
        },
        {
          "name": "Civil Hospital",
          "distance": "1.5 km",
          "distanceKm": 1.5,
          "queue": 40,
          "beds": {"general": 30, "icu": 12},
          "specialties": ["Emergency", "Government", "Teaching"],
          "rating": 3.6,
          "phone": "+91-79-2214-1911",
          "address": "Asarwa, Ahmedabad",
        },
      ],

      "Chandigarh": [
        {
          "name": "PGIMER Chandigarh",
          "distance": "3.1 km",
          "distanceKm": 3.1,
          "queue": 22,
          "beds": {"general": 18, "icu": 7},
          "specialties": ["All Specialties", "Research", "Teaching"],
          "rating": 4.7,
          "phone": "+91-172-275-5555",
          "address": "Sector 12, Chandigarh",
        },
        {
          "name": "Fortis Hospital Mohali",
          "distance": "5.0 km",
          "distanceKm": 5.0,
          "queue": 7,
          "beds": {"general": 7, "icu": 3},
          "specialties": ["Cardiology", "Neurology"],
          "rating": 4.5,
          "phone": "+91-172-4692-222",
          "address": "Sector 62, Phase VIII, Mohali",
        },
        {
          "name": "Max Super Specialty Mohali",
          "distance": "6.4 km",
          "distanceKm": 6.4,
          "queue": 8,
          "beds": {"general": 6, "icu": 2},
          "specialties": ["Orthopedics", "Oncology"],
          "rating": 4.4,
          "phone": "+91-172-3988-000",
          "address": "Civil Hospital Road, Sector 53B, Chandigarh",
        },
      ],

      "Kochi": [
        {
          "name": "Aster Medcity",
          "distance": "4.5 km",
          "distanceKm": 4.5,
          "queue": 10,
          "beds": {"general": 10, "icu": 4},
          "specialties": ["Multi-Specialty", "Transplant"],
          "rating": 4.7,
          "phone": "+91-484-6699-999",
          "address": "Kuttisahib Road, Cheranalloor, Kochi",
        },
        {
          "name": "Amrita Institute of Medical Sciences",
          "distance": "7.2 km",
          "distanceKm": 7.2,
          "queue": 18,
          "beds": {"general": 15, "icu": 6},
          "specialties": ["Oncology", "Cardiology", "Neurology"],
          "rating": 4.8,
          "phone": "+91-484-2851-234",
          "address": "AIMS Ponekkara, Edappally, Kochi",
        },
        {
          "name": "Rajagiri Hospital",
          "distance": "3.2 km",
          "distanceKm": 3.2,
          "queue": 6,
          "beds": {"general": 7, "icu": 2},
          "specialties": ["Orthopedics", "Gastroenterology"],
          "rating": 4.5,
          "phone": "+91-484-2905-000",
          "address": "Chunangamvely, Aluva, Kochi",
        },
      ],
    };
  }
}