// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBlLiHS9WPOmH4pBg9xpbXy-9DuhTCsyuE',
    appId: '1:613403166927:web:38a456945f7f224013cfba',
    messagingSenderId: '613403166927',
    projectId: 'hospital-1792a',
    authDomain: 'hospital-1792a.firebaseapp.com',
    storageBucket: 'hospital-1792a.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCn4y19y2TnLZ-pCWYi2rtpelmE9twVP9o',
    appId: '1:613403166927:android:207f3022c92c695213cfba',
    messagingSenderId: '613403166927',
    projectId: 'hospital-1792a',
    storageBucket: 'hospital-1792a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDN0XSWXBlzbwa-3mkEM-yQKm9FKruxhFA',
    appId: '1:613403166927:ios:89786bd99063e57c13cfba',
    messagingSenderId: '613403166927',
    projectId: 'hospital-1792a',
    storageBucket: 'hospital-1792a.firebasestorage.app',
    iosBundleId: 'com.example.hospital',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDN0XSWXBlzbwa-3mkEM-yQKm9FKruxhFA',
    appId: '1:613403166927:ios:89786bd99063e57c13cfba',
    messagingSenderId: '613403166927',
    projectId: 'hospital-1792a',
    storageBucket: 'hospital-1792a.firebasestorage.app',
    iosBundleId: 'com.example.hospital',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBlLiHS9WPOmH4pBg9xpbXy-9DuhTCsyuE',
    appId: '1:613403166927:web:ec8ae996bd3db9e813cfba',
    messagingSenderId: '613403166927',
    projectId: 'hospital-1792a',
    authDomain: 'hospital-1792a.firebaseapp.com',
    storageBucket: 'hospital-1792a.firebasestorage.app',
  );
}
